RSpec.describe NumbersTranslator do

  describe 'returns the correct string, param lang == uk' do
    example = [
        ['one', 01],
        ['one', 001],
        ['one', 1],
        ['five', 5],
        ['nine', 9],
        ['ten', 10],
        ['fourteen', 14],
        ['nineteen', 19],
        ['twenty', 20],
        ['twenty-five', 25],
        ['twenty-nine', 29],
        ['sixty-eight', 68],
        ['ninety-nine', 99],
        ['one hundred', 100],
        ['one hundred and five', 105],
        ['one hundred and ten', 110],
        ['one hundred and seventeen', 117],
        ['one hundred and forty', 140],
        ['one hundred and sixty-three', 163],
        ['one thousand', 1000],
        ['one thousand and five', 1005],
        ['one thousand and eleven', 1011],
        ['one thousand and twenty-three', 1023],
        ['one thousand four hundred and fifty-five', 1455],
        ['ten thousand', 10000],
        ['ten thousand and seven', 10007],
        ['ten thousand and seventeen', 10017],
        ['ten thousand and seventy-seven', 10077],
        ['ten thousand one hundred and seven', 10107],
        ['ten thousand one hundred and seventy-seven', 10177],
        ['fourteen thousand one hundred and seventy-seven', 14177],
        ['one hundred thousand', 100000],
        ['one hundred thousand and two', 100002],
        ['one hundred thousand and sixteen', 100016],
        ['one hundred thousand one hundred and six', 100106],
        ['one hundred and seven thousand one hundred and six', 107106],
        ['one hundred and eighty-seven thousand one hundred and six', 187106],
        ['one hundred and eighty-seven thousand one hundred and sixteen', 187116],
        ['one hundred and eighty-seven thousand one hundred and fifty-six', 187156],
        ['one hundred and sixty-three thousand and four', 163004],
        ['two million', 2000000],
        ['two million and one', 2000001],
        ['two million and thirteen', 2000013],
        ['two million and forty-eight', 2000048],
        ['two million two hundred and forty-eight', 2000248],
        ['two million and one thousand and forty-eight', 2001048],
        ['two million and fifteen thousand and forty-eight', 2015048],
        ['two million and eighty-five thousand and forty-eight', 2085048],
        ['two million seven hundred and five thousand and forty-eight', 2705048],
        ['two million one hundred and twenty-five thousand and forty-eight', 2125048],
        ['two million five hundred and fifty-five thousand and forty-eight', 2555048],
        ['twenty million', 20000000],
        ['twenty million and one', 20000001],
        ['twenty million and thirteen', 20000013],
        ['twenty million and forty-eight', 20000048],
        ['twenty million two hundred and forty-eight', 20000248],
        ['twenty million and ten thousand and forty-eight', 20010048],
        ['twenty million eight hundred and fifty thousand and forty-eight', 20850048],
        ['twenty-seven million and fifteen thousand and forty-eight', 27015048],
        ['twenty-one million two hundred and fifteen thousand and forty-eight', 21215048],
        ['twenty-one million five hundred and fifty-five thousand and forty-eight', 21555048],
        ['two hundred million', 200000000],
        ['two hundred million and one', 200000001],
        ['two hundred million and thirteen', 200000013],
        ['two hundred million and forty-eight', 200000048],
        ['two hundred million two hundred and forty-eight', 200000248],
        ['two hundred million one hundred thousand and forty-eight', 200100048],
        ['two hundred and eight million five hundred thousand and forty-eight', 208500048],
        ['two hundred and seventy million and fifteen thousand and forty-eight', 270015048],
        ['two hundred and ten million two hundred and fifteen thousand and forty-eight', 210215048],
        ['two hundred and fifteen million and fifty-five thousand and forty-eight', 215055048],
        ['nine billion', 9000000000],
        ['eight billion and one', 8000000001],
        ['seven billion and thirteen', 7000000013],
        ['six billion and forty-eight', 6000000048],
        ['five billion two hundred and forty-eight', 5000000248],
        ['four billion and one million and forty-eight', 4001000048],
        ['three billion and eight million five hundred thousand and forty-eight', 3008500048],
        ['two billion seven hundred million and fifteen thousand and forty-eight', 2700015048],
        ['two billion one hundred and two million and fifteen thousand and forty-eight', 2102015048],
        ['four billion one hundred and fifty million five hundred and five thousand and forty-eight', 4150505048],
        ['two billion and one million five hundred thousand and forty-eight', 2001500048],
        ['forty-five billion one hundred and sixty-eight million and fifteen thousand and sixty', 45168015060],
        ['five hundred and seventy-six billion and sixty-four million eight hundred and twenty thousand seven hundred and sixteen', 576064820716],
        ['four trillion seven hundred and twenty-one billion five hundred and six million and ninety-eight thousand five hundred and twelve', 4721506098512],
        ['ninety-seven trillion five hundred and forty-two billion and fifty million six hundred and forty thousand seven hundred', 97542050640700],
        ['five hundred and seventy trillion one hundred and sixty billion five hundred and seventy million four hundred and eighty-four thousand and twenty-six', 570160570484026],
        ['eight quadrillion seven hundred and fifty-four trillion six hundred and nineteen billion two hundred and four million five hundred and five thousand seven hundred and six', 8754619204505706]
    ]

    example.each do |value|
      it "test for example #{value[1]}" do
        expect(NumbersTranslator::Translator.make value[1]).to eq(value[0])
      end
    end
  end

  describe 'returns the correct string, param lang == usa' do
    example = [
        ['one', 1, 'usa'],
        ['five', 5, 'usa'],
        ['nine', 9, 'usa'],
        ['ten', 10, 'usa'],
        ['fourteen', 14, 'usa'],
        ['nineteen', 19, 'usa'],
        ['twenty', 20, 'usa'],
        ['twenty-five', 25, 'usa'],
        ['twenty-nine', 29, 'usa'],
        ['sixty-eight', 68, 'usa'],
        ['ninety-nine', 99, 'usa'],
        ['one hundred', 100, 'usa'],
        ['one hundred five', 105, 'usa'],
        ['one hundred ten', 110, 'usa'],
        ['one hundred seventeen', 117, 'usa'],
        ['one hundred forty', 140, 'usa'],
        ['one hundred sixty-three', 163, 'usa'],
        ['one thousand', 1000, 'usa'],
        ['one thousand five', 1005, 'usa'],
        ['one thousand eleven', 1011, 'usa'],
        ['one thousand twenty-three', 1023, 'usa'],
        ['one thousand four hundred fifty-five', 1455, 'usa'],
        ['ten thousand', 10000, 'usa'],
        ['ten thousand seven', 10007, 'usa'],
        ['ten thousand seventeen', 10017, 'usa'],
        ['ten thousand seventy-seven', 10077, 'usa'],
        ['ten thousand one hundred seven', 10107, 'usa'],
        ['ten thousand one hundred seventy-seven', 10177, 'usa'],
        ['fourteen thousand one hundred seventy-seven', 14177, 'usa'],
        ['one hundred thousand', 100000, 'usa'],
        ['one hundred thousand two', 100002, 'usa'],
        ['one hundred thousand sixteen', 100016, 'usa'],
        ['one hundred thousand one hundred six', 100106, 'usa'],
        ['one hundred seven thousand one hundred six', 107106, 'usa'],
        ['one hundred eighty-seven thousand one hundred six', 187106, 'usa'],
        ['one hundred eighty-seven thousand one hundred sixteen', 187116, 'usa'],
        ['one hundred eighty-seven thousand one hundred fifty-six', 187156, 'usa'],
        ['one hundred sixty-three thousand four', 163004, 'usa'],
        ['two million', 2000000, 'usa'],
        ['two million one', 2000001, 'usa'],
        ['two million thirteen', 2000013, 'usa'],
        ['two million forty-eight', 2000048, 'usa'],
        ['two million two hundred forty-eight', 2000248, 'usa'],
        ['two million one thousand forty-eight', 2001048, 'usa'],
        ['two million fifteen thousand forty-eight', 2015048, 'usa'],
        ['two million eighty-five thousand forty-eight', 2085048, 'usa'],
        ['two million seven hundred five thousand forty-eight', 2705048, 'usa'],
        ['two million one hundred twenty-five thousand forty-eight', 2125048, 'usa'],
        ['two million five hundred fifty-five thousand forty-eight', 2555048, 'usa'],
        ['twenty million', 20000000, 'usa'],
        ['twenty million one', 20000001, 'usa'],
        ['twenty million thirteen', 20000013, 'usa'],
        ['twenty million forty-eight', 20000048, 'usa'],
        ['twenty million two hundred forty-eight', 20000248, 'usa'],
        ['twenty million ten thousand forty-eight', 20010048, 'usa'],
        ['twenty million eight hundred fifty thousand forty-eight', 20850048, 'usa'],
        ['twenty-seven million fifteen thousand forty-eight', 27015048, 'usa'],
        ['twenty-one million two hundred fifteen thousand forty-eight', 21215048, 'usa'],
        ['twenty-one million five hundred fifty-five thousand forty-eight', 21555048, 'usa'],
        ['two hundred million', 200000000, 'usa'],
        ['two hundred million one', 200000001, 'usa'],
        ['two hundred million thirteen', 200000013, 'usa'],
        ['two hundred million forty-eight', 200000048, 'usa'],
        ['two hundred million two hundred forty-eight', 200000248, 'usa'],
        ['two hundred million one hundred thousand forty-eight', 200100048, 'usa'],
        ['two hundred eight million five hundred thousand forty-eight', 208500048, 'usa'],
        ['two hundred seventy million fifteen thousand forty-eight', 270015048, 'usa'],
        ['two hundred ten million two hundred fifteen thousand forty-eight', 210215048, 'usa'],
        ['two hundred fifteen million fifty-five thousand forty-eight', 215055048, 'usa'],
        ['nine billion', 9000000000, 'usa'],
        ['eight billion one', 8000000001, 'usa'],
        ['seven billion thirteen', 7000000013, 'usa'],
        ['six billion forty-eight', 6000000048, 'usa'],
        ['five billion two hundred forty-eight', 5000000248, 'usa'],
        ['four billion one million forty-eight', 4001000048, 'usa'],
        ['three billion eight million five hundred thousand forty-eight', 3008500048, 'usa'],
        ['two billion seven hundred million fifteen thousand forty-eight', 2700015048, 'usa'],
        ['two billion one hundred two million fifteen thousand forty-eight', 2102015048, 'usa'],
        ['four billion one hundred fifty million five hundred five thousand forty-eight', 4150505048, 'usa'],
        ['two billion one million five hundred thousand forty-eight', 2001500048, 'usa'],
        ['forty-five billion one hundred sixty-eight million fifteen thousand sixty', 45168015060, 'usa'],
        ['five hundred seventy-six billion sixty-four million eight hundred twenty thousand seven hundred sixteen', 576064820716, 'usa'],
        ['four trillion seven hundred twenty-one billion five hundred six million ninety-eight thousand five hundred twelve', 4721506098512, 'usa'],
        ['ninety-seven trillion five hundred forty-two billion fifty million six hundred forty thousand seven hundred', 97542050640700, 'usa'],
        ['five hundred seventy trillion one hundred sixty billion five hundred seventy million four hundred eighty-four thousand twenty-six', 570160570484026, 'usa'],
        ['eight quadrillion seven hundred fifty-four trillion six hundred nineteen billion two hundred four million five hundred five thousand seven hundred six', 8754619204505706, 'usa']
    ]

    example.each do |value|
      it "test for example #{value[1]}" do
        expect(NumbersTranslator::Translator.make value[1], value[3]).to eq(value[0])
      end
    end
  end

  it 'raises ArgumentError exception' do
    expect{ NumbersTranslator::Translator.make 11111111111111111 }.to raise_error(ArgumentError)
  end

end
